import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";

import { loadConfig } from "./config.js";
import { fitLines, renderBudgetNotice } from "./budget.js";
import { Index } from "./db.js";
import type { Entry } from "./mdStore.js";
import { indexDb, memoryRoot, namespaceFor, namespaces, nsDir, rootDir, txnLog } from "./paths.js";
import { sanitizeForInjection } from "./sanitize.js";
import { selectStatic } from "./select.js";
import { atomicWrite, withFileLock } from "./transaction.js";

const START_MARKER = "<!-- memcore:start -->";
const END_MARKER = "<!-- memcore:end -->";

function oneLine(content: string, max = 80): string {
  const flat = content.replaceAll("\n", " ");
  return flat.length > max ? flat.slice(0, max - 1) + "…" : flat;
}

function entryLine(e: Entry): string {
  return `- [${e.entryId}] ${oneLine(e.content)} (${e.kind.toLowerCase()}, use=${e.useCount}, score=${e.valueScore.toFixed(2)})`;
}

export async function renderIndexMarkdown(idx: Index): Promise<string> {
  const root = rootDir();
  const lines = [
    "# Memcore Memory Index",
    "",
    "> Auto-generated by memcore (memcore index). Markdown is the source of truth, organized by namespace; edit the md files directly.",
    "",
  ];
  const nss = namespaces(root);
  if (!nss.length) {
    lines.push("_No namespaces yet._");
    lines.push("");
  }
  for (const ns of nss) {
    const counts = idx.counts()[ns] ?? {};
    const top = selectStatic(idx, { ns, topN: 5 });
    lines.push(`## ${ns}`, "");
    lines.push(`- Path: \`${nsDir(root, ns)}\``);
    const stats = Object.entries(counts).map(([k, v]) => `${k}=${v}`).join(", ");
    lines.push(`- Stats: ${stats || "empty"}`);
    if (top.length) {
      lines.push("", "Top entries (by value score):", "", ...top.map(entryLine));
    }
    lines.push("");
  }
  lines.push("## Usage", "");
  lines.push("1. Read this file at the start of a new session for a memory overview.");
  lines.push("2. Read the namespace's MEMORY.md / USER.md for details.");
  lines.push("3. memcore MCP tools: memory_search / memory_remember / memory_forget / memory_status.");
  lines.push("");
  return lines.join("\n");
}

export function renderBaselineSection(ns: string, topEntries: Entry[], maxTokens?: number): string {
  const root = rootDir();
  const lines = topEntries
    .filter((e) => sanitizeForInjection(e.content).safe)
    .map(entryLine);
  const fitted = fitLines(lines, maxTokens ?? 1500);
  const body = [
    START_MARKER,
    "## Memory system (memcore)",
    "",
    "Long-term memory is maintained by memcore. Markdown files are the source of truth (human-readable, hand-editable):",
    `- Global index: \`${join(memoryRoot(root), "INDEX.md")}\``,
    `- This namespace MEMORY.md: \`${join(nsDir(root, ns), "MEMORY.md")}\``,
    `- This namespace USER.md: \`${join(nsDir(root, ns), "USER.md")}\``,
    "",
    fitted.lines.length
      ? "Injected memories (by value score):"
      : "(No memories in this namespace yet; use memory_remember to save one)",
    ...fitted.lines,
    renderBudgetNotice(fitted.truncated),
    "",
    "Memory tools (MCP): memory_search / memory_remember / memory_forget / memory_status.",
    END_MARKER,
  ];
  return body.filter((l) => l !== "").join("\n") + "\n";
}

export function updateAgentsMd(workdir: string, section: string): void {
  const path = join(workdir, "AGENTS.md");
  const lockPath = join(
    rootDir(),
    "state",
    "locks",
    `${createHash("sha1").update(resolve(path)).digest("hex")}.lock`,
  );
  withFileLock(lockPath, () => {
    const existing = existsSync(path) ? readFileSync(path, "utf-8") : "";
    const start = existing.indexOf(START_MARKER);
    const end = existing.indexOf(END_MARKER);
    let next: string;
    if (start >= 0 && end >= 0) {
      next = existing.slice(0, start) + section + existing.slice(end + END_MARKER.length).replace(/^\n/, "");
    } else if (start >= 0 || end >= 0) {
      throw new Error("AGENTS.md contains unmatched memcore marker");
    } else {
      next = existing.trimEnd() ? existing.trimEnd() + "\n\n" + section : section;
    }
    atomicWrite(path, next);
  });
}

export async function generateIndex(): Promise<string> {
  const root = rootDir();
  const idx = await Index.create(indexDb(root));
  try {
    const content = await renderIndexMarkdown(idx);
    atomicWrite(join(memoryRoot(root), "INDEX.md"), content);
    idx.audit("index", "-", `regenerated INDEX.md`);
    return content;
  } finally {
    idx.close();
  }
}

export async function injectBaseline(workdir: string, topN?: number): Promise<number> {
  const root = rootDir();
  const config = loadConfig(root);
  const ns = namespaceFor(workdir);
  const idx = await Index.create(indexDb(root));
  try {
    const n = topN ?? config.budget.topKStatic;
    const top = selectStatic(idx, { ns, kinds: ["MEMORY", "USER"], topN: n });
    const blocked = top.filter((e) => !sanitizeForInjection(e.content).safe).length;
    const safe = top.filter((e) => sanitizeForInjection(e.content).safe);
    const fitted = fitLines(safe.map(entryLine), config.budget.maxInjectTokens);
    updateAgentsMd(workdir, renderBaselineSection(ns, top, config.budget.maxInjectTokens));
    idx.audit("baseline", ns, `${workdir} -> ${fitted.lines.length} injected of ${top.length}${blocked ? ` (${blocked} blocked by injection scan)` : ""}`);
    return fitted.lines.length;
  } finally {
    idx.close();
  }
}
